# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rbackend.proto\".\n\x0cMusicRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x10\n\x08music_id\x18\x02 \x01(\x03\",\n\x08RankInfo\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x12\n\nrankNumber\x18\x02 \x01(\x03\x32=\n\x07\x42\x61\x63kend\x12\x32\n\x14GetDownloadRankDaily\x12\r.MusicRequest\x1a\t.RankInfo\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MUSICREQUEST = _descriptor.Descriptor(
  name='MusicRequest',
  full_name='MusicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='MusicRequest.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='music_id', full_name='MusicRequest.music_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=63,
)


_RANKINFO = _descriptor.Descriptor(
  name='RankInfo',
  full_name='RankInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='RankInfo.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankNumber', full_name='RankInfo.rankNumber', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['MusicRequest'] = _MUSICREQUEST
DESCRIPTOR.message_types_by_name['RankInfo'] = _RANKINFO

MusicRequest = _reflection.GeneratedProtocolMessageType('MusicRequest', (_message.Message,), dict(
  DESCRIPTOR = _MUSICREQUEST,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:MusicRequest)
  ))
_sym_db.RegisterMessage(MusicRequest)

RankInfo = _reflection.GeneratedProtocolMessageType('RankInfo', (_message.Message,), dict(
  DESCRIPTOR = _RANKINFO,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:RankInfo)
  ))
_sym_db.RegisterMessage(RankInfo)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class BackendStub(object):
  """The backend computation result retrieval service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDownloadRankDaily = channel.unary_unary(
        '/Backend/GetDownloadRankDaily',
        request_serializer=MusicRequest.SerializeToString,
        response_deserializer=RankInfo.FromString,
        )


class BackendServicer(object):
  """The backend computation result retrieval service
  """

  def GetDownloadRankDaily(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BackendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDownloadRankDaily': grpc.unary_unary_rpc_method_handler(
          servicer.GetDownloadRankDaily,
          request_deserializer=MusicRequest.FromString,
          response_serializer=RankInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Backend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaBackendServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  """The backend computation result retrieval service
  """
  def GetDownloadRankDaily(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaBackendStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  """The backend computation result retrieval service
  """
  def GetDownloadRankDaily(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  GetDownloadRankDaily.future = None


def beta_create_Backend_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('Backend', 'GetDownloadRankDaily'): MusicRequest.FromString,
  }
  response_serializers = {
    ('Backend', 'GetDownloadRankDaily'): RankInfo.SerializeToString,
  }
  method_implementations = {
    ('Backend', 'GetDownloadRankDaily'): face_utilities.unary_unary_inline(servicer.GetDownloadRankDaily),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_Backend_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('Backend', 'GetDownloadRankDaily'): MusicRequest.SerializeToString,
  }
  response_deserializers = {
    ('Backend', 'GetDownloadRankDaily'): RankInfo.FromString,
  }
  cardinalities = {
    'GetDownloadRankDaily': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'Backend', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
